const greek = [
  ["\\alpha", -1],
  ["\\beta", -1],
  ["\\gamma", -1],
  ["\\Gamma", -1],
  ["\\delta", -1],
  ["\\Delta", -1],
  ["\\epsilon", -1],
  ["\\varepsilon", -1],
  ["\\zeta", -1],
  ["\\eta", -1],
  ["\\theta", -1],
  ["\\vartheta", -1],
  ["\\iota", -1],
  ["\\kappa", -1],
  ["\\lambda", -1],
  ["\\Lambda", -1],
  ["\\mu", -1],
  ["\\nu", -1],
  ["\\xi", -1],
  ["\\omicron", -1],
  ["\\Pi", -1],
  ["\\pi", -1],
  ["\\varpi", -1],
  ["\\rho", -1],
  ["\\varrho", -1],
  ["\\Sigma", -1],
  ["\\sigma", -1],
  ["\\varsigma", -1],
  ["\\tau", -1],
  ["\\Upsilon", -1],
  ["\\Phi", -1],
  ["\\phi", -1],
  ["\\varphi", -1],
  ["\\chi", -1],
  ["\\Psi", -1],
  ["\\psi", -1],
  ["\\Omega", -1],
  ["\\omega", -1]
];

const relation = [
  ["<", -1],
  ["\\nless", -1],
  ["\\leq", -1],
  ["\\leqslant", -1],
  ["\\nleq", -1],
  ["\\nleqslant", -1],
  ["\\prec", -1],
  ["\\nprec", -1],
  ["\\preceq", -1],
  ["\\npreceq", -1],
  ["\\ll", -1],
  ["\\lll", -1],
  ["\\subset", -1],
  ["\\not\\subset", -1],
  ["\\subseteq", -1],
  ["\\nsubseteq", -1],
  ["\\sqsubset", -1],
  ["\\sqsubseteq", -1],
  [">", -1],
  ["\\ngtr", -1],
  ["\\geq", -1],
  ["\\geqslant", -1],
  ["\\ngeq", -1],
  ["\\ngeqslant", -1],
  ["\\succ", -1],
  ["\\nsucc", -1],
  ["\\succeq", -1],
  ["\\nsucceq", -1],
  ["\\gg", -1],
  ["\\ggg", -1],
  ["\\supset", -1],
  ["\\not\\supset", -1],
  ["\\supseteq", -1],
  ["\\nsupseteq", -1],
  ["\\sqsupset", -1],
  ["\\sqsupseteq", -1],
  ["=", -1],
  ["\\doteq", -1],
  ["\\equiv", -1],
  ["\\approx", -1],
  ["\\cong", -1],
  ["\\simeq", -1],
  ["\\sim", -1],
  ["\\propto", -1],
  ["\\neq", -1]
]

const logic = [
  ["\\exists", -1],
  ["\\exists!", -1],
  ["\\nexists", -1],
  ["\\forall", -1],
  ["\\neg", -1],
  ["\\lor", -1],
  ["\\land", -1],
  ["\\Longrightarrow", -1],//implies
  ["\\Rightarrow", -1],
  ["\\Longleftarrow", -1],
  ["\\Leftarrow", -1],
  ["\\iff", -1],
  ["\\Leftrightarrow", -1],
  ["\\top", -1],
  ["\\bot", -1]
]

const geometry = [
  ["\\overline{\\rm AB}", -1],
  ["\\angle", -1],
  ["\\triangle", -1],
  ["\\cong", -1],
  [" \\sim", -1],
  ["\\|", -1],
  ["\\perp", -1],
  ["\\overrightarrow{\\rm AB}", -1],
  ["\\measuredangle", -1],
  ["\\square", -1],
  ["\\parallel", -1],
  ["\\asymp", -1],
  ["\\vdash", -1],
  ["\\in", -1],
  ["\\smile", -1],
  ["\\models", -1],
  ["\\perp", -1],
  ["\\nparallel", -1],
  ["\\bowtie", -1],
  ["\\dashv", -1],
  ["\\ni", -1],
  ["\\frown", -1],
  ["\\notin", -1],
  ["\\mid", -1],
  ["\\ncong", -1],
  ["\\nsim", -1],
  ["\\nparallel", -1],
  ["\\not\\perp", -1]
]

const binary = [
  ["\\pm", -1],
  ["\\mp", -1],
  ["\\times", -1],
  ["\\div", -1],
  ["\\ast", -1],
  ["\\star", -1],
  ["\\dagger", -1],
  ["\\ddagger", -1],
  ["\\cap", -1],
  ["\\cup", -1],
  ["\\uplus", -1],
  ["\\sqcap", -1],
  ["\\sqcup", -1],
  ["\\vee", -1],
  ["\\wedge", -1],
  ["\\cdot", -1],
  ["\\diamond", -1],
  ["\\bigtriangleup", -1],
  ["\\bigtriangledown", -1],
  ["\\triangleleft", -1],
  ["\\triangleright", -1],
  ["\\bigcirc", -1],
  ["\\bullet", -1],
  ["\\wr", -1],
  ["\\oplus", -1],
  ["\\ominus", -1],
  ["\\otimes", -1],
  ["\\oslash", -1],
  ["\\odot", -1],
  ["\\circ", -1],
  ["\\setminus", -1],
  ["\\amalg", -1]
]

const arrows = [
  ["\\rightarrow", -1],
  ["\\to", -1],
  ["\\mapsto", -1],
  ["\\leftarrow", -1],
  ["\\gets", -1],
  ["\\Rightarrow", -1],
  ["\\Leftarrow", -1],
  ["\\longrightarrow", -1],
  ["\\longmapsto", -1],
  ["\\longleftarrow", -1],
  ["\\Longrightarrow", -1],
  ["\\Longleftarrow", -1],
  ["\\uparrow", -1],
  ["\\downarrow", -1],
  ["\\updownarrow", -1],
  ["\\Uparrow", -1],
  ["\\Downarrow", -1],
  ["\\Updownarrow", -1]
]

const sets =[
  ["\\emptyset", -1],
  ["\\varnothing", -1],
  ["\\N", -1],
  ["\\Z", -1],
  ["\\mathbb{Q}", -1],
  ["\\mathbb{A}", -1],
  ["\\R", -1],
  ["\\mathbb{C}", -1],
  ["\\mathbb{I}", -1],
  ["\\mathbb{H}", -1],
  ["\\mathbb{O}", -1],
  ["\\mathbb{S}", -1],
  ["\\in", -1],
  ["\\notin", -1],
  ["\\ni", -1],
  ["\\subset", -1],
  ["\\subseteq", -1],
  ["\\supset", -1],
  ["\\supseteq", -1],
  ["\\cup", -1],
  ["\\cap", -1],
  ["\\setminus", -1]
]

const other_symbols = [
  ["\\partial", -1],
  ["\\eth", -1],
  ["\\hbar", -1],
  ["\\imath", -1],
  ["\\jmath", -1],
  ["\\ell", -1],
  ["\\Re", -1],
  ["\\Im", -1],
  ["\\wp", -1],
  ["\\nabla", -1],
  ["\\Box", -1],
  ["\\infty", -1]
]

const symbols = [
  { name: 'Greek', symbols: greek },
  { name: 'Relation', symbols: relation },
  { name: 'Logic', symbols: logic },
  { name: 'Geometry', symbols: geometry },
  { name: 'Binary', symbols: binary },
  { name: 'Arrows', symbols: arrows },
  { name: 'Sets', symbols: sets },
  { name: 'Other Symbols', symbols: other_symbols }
]

export default symbols;