const greek = [
  ["\\alpha", 0],
  ["\\beta", 0],
  ["\\gamma", 0],
  ["\\Gamma", 0],
  ["\\delta", 0],
  ["\\Delta", 0],
  ["\\epsilon", 0],
  ["\\varepsilon", 0],
  ["\\zeta", 0],
  ["\\eta", 0],
  ["\\theta", 0],
  ["\\vartheta", 0],
  ["\\iota", 0],
  ["\\kappa", 0],
  ["\\lambda", 0],
  ["\\Lambda", 0],
  ["\\mu", 0],
  ["\\nu", 0],
  ["\\xi", 0],
  ["\\omicron", 0],
  ["\\Pi", 0],
  ["\\pi", 0],
  ["\\varpi", 0],
  ["\\rho", 0],
  ["\\varrho", 0],
  ["\\Sigma", 0],
  ["\\sigma", 0],
  ["\\varsigma", 0],
  ["\\tau", 0],
  ["\\Upsilon", 0],
  ["\\Phi", 0],
  ["\\phi", 0],
  ["\\varphi", 0],
  ["\\chi", 0],
  ["\\Psi", 0],
  ["\\psi", 0],
  ["\\Omega", 0],
  ["\\omega", 0]
];

const relation = [
  ["<", 0],
  ["\\nless", 0],
  ["\\leq", 0],
  ["\\leqslant", 0],
  ["\\nleq", 0],
  ["\\nleqslant", 0],
  ["\\prec", 0],
  ["\\nprec", 0],
  ["\\preceq", 0],
  ["\\npreceq", 0],
  ["\\ll", 0],
  ["\\lll", 0],
  ["\\subset", 0],
  ["\\not\\subset", 0],
  ["\\subseteq", 0],
  ["\\nsubseteq", 0],
  ["\\sqsubset", 0],
  ["\\sqsubseteq", 0],
  [">", 0],
  ["\\ngtr", 0],
  ["\\geq", 0],
  ["\\geqslant", 0],
  ["\\ngeq", 0],
  ["\\ngeqslant", 0],
  ["\\succ", 0],
  ["\\nsucc", 0],
  ["\\succeq", 0],
  ["\\nsucceq", 0],
  ["\\gg", 0],
  ["\\ggg", 0],
  ["\\supset", 0],
  ["\\not\\supset", 0],
  ["\\supseteq", 0],
  ["\\nsupseteq", 0],
  ["\\sqsupset", 0],
  ["\\sqsupseteq", 0],
  ["=", 0],
  ["\\doteq", 0],
  ["\\equiv", 0],
  ["\\approx", 0],
  ["\\cong", 0],
  ["\\simeq", 0],
  ["\\sim", 0],
  ["\\propto", 0],
  ["\\neq", 0]
]

const logic = [
  ["\\exists", 0],
  ["\\exists!", 0],
  ["\\nexists", 0],
  ["\\forall", 0],
  ["\\neg", 0],
  ["\\lor", 0],
  ["\\land", 0],
  ["\\Longrightarrow", 0],//implies
  ["\\Rightarrow", 0],
  ["\\Longleftarrow", 0],
  ["\\Leftarrow", 0],
  ["\\iff", 0],
  ["\\Leftrightarrow", 0],
  ["\\top", 0],
  ["\\bot", 0]
]

const geometry = [
  ["\\overline{\\rm AB}", 0],
  ["\\angle", 0],
  ["\\triangle", 0],
  ["\\cong", 0],
  [" \\sim", 0],
  ["\\|", 0],
  ["\\perp", 0],
  ["\\overrightarrow{\\rm AB}", 0],
  ["\\measuredangle", 0],
  ["\\square", 0],
  ["\\parallel", 0],
  ["\\asymp", 0],
  ["\\vdash", 0],
  ["\\in", 0],
  ["\\smile", 0],
  ["\\models", 0],
  ["\\perp", 0],
  ["\\nparallel", 0],
  ["\\bowtie", 0],
  ["\\dashv", 0],
  ["\\ni", 0],
  ["\\frown", 0],
  ["\\notin", 0],
  ["\\mid", 0],
  ["\\ncong", 0],
  ["\\nsim", 0],
  ["\\nparallel", 0],
  ["\\not\\perp", 0]
]

const binary = [
  ["\\pm", 0],
  ["\\mp", 0],
  ["\\times", 0],
  ["\\div", 0],
  ["\\ast", 0],
  ["\\star", 0],
  ["\\dagger", 0],
  ["\\ddagger", 0],
  ["\\cap", 0],
  ["\\cup", 0],
  ["\\uplus", 0],
  ["\\sqcap", 0],
  ["\\sqcup", 0],
  ["\\vee", 0],
  ["\\wedge", 0],
  ["\\cdot", 0],
  ["\\diamond", 0],
  ["\\bigtriangleup", 0],
  ["\\bigtriangledown", 0],
  ["\\triangleleft", 0],
  ["\\triangleright", 0],
  ["\\bigcirc", 0],
  ["\\bullet", 0],
  ["\\wr", 0],
  ["\\oplus", 0],
  ["\\ominus", 0],
  ["\\otimes", 0],
  ["\\oslash", 0],
  ["\\odot", 0],
  ["\\circ", 0],
  ["\\setminus", 0],
  ["\\amalg", 0]
]

const arrows = [
  ["\\rightarrow", 0],
  ["\\to", 0],
  ["\\mapsto", 0],
  ["\\leftarrow", 0],
  ["\\gets", 0],
  ["\\Rightarrow", 0],
  ["\\Leftarrow", 0],
  ["\\longrightarrow", 0],
  ["\\longmapsto", 0],
  ["\\longleftarrow", 0],
  ["\\Longrightarrow", 0],
  ["\\Longleftarrow", 0],
  ["\\uparrow", 0],
  ["\\downarrow", 0],
  ["\\updownarrow", 0],
  ["\\Uparrow", 0],
  ["\\Downarrow", 0],
  ["\\Updownarrow", 0],
  ["\\circlearrowright", 0],
  ["\\curvearrowleft", 0],
  ["\\searrow", 0]
]

const sets =[
  ["\\emptyset", 0],
  ["\\varnothing", 0],
  ["\\N", 0],
  ["\\Z", 0],
  ["\\mathbb{Q}", 0],
  ["\\mathbb{A}", 0],
  ["\\R", 0],
  ["\\mathbb{C}", 0],
  ["\\mathbb{I}", 0],
  ["\\mathbb{H}", 0],
  ["\\mathbb{O}", 0],
  ["\\mathbb{S}", 0],
  ["\\in", 0],
  ["\\notin", 0],
  ["\\ni", 0],
  ["\\subset", 0],
  ["\\subseteq", 0],
  ["\\supset", 0],
  ["\\supseteq", 0],
  ["\\cup", 0],
  ["\\cap", 0],
  ["\\setminus", 0]
]

const other_symbols = [
  ["\\partial", 0],
  ["\\eth", 0],
  ["\\hbar", 0],
  ["\\imath", 0],
  ["\\jmath", 0],
  ["\\ell", 0],
  ["\\Re", 0],
  ["\\Im", 0],
  ["\\wp", 0],
  ["\\nabla", 0],
  ["\\Box", 0],
  ["\\infty", 0],
  ["|", 0],
  ["(\,", 0],
  ["\\{", 0],
  ["\\lceil", 0],
  ["\\ulcorner", 0],
  ["\\|", 0],
  [")\,", 0],//maybe )\\,
  ["\\}", 0],
  ["\\rceil", 0],
  ["\\urcorner", 0],
  ["/", 0],
  ["\\[\,", 0],//maybe \\[\\,
  ["\\langle", 0],
  ["\\lfloor", 0],
  ["\\llcorner", 0],
  ["\\backslash", 0],
  ["\\]\,", 0],//maybe \\]\\,
  ["\\rangle", 0],
  ["\\rfloor", 0],
  ["\\lrcorner", 0] 
]

const symbols = [
  { name: 'Greek', symbols: greek },
  { name: 'Relation', symbols: relation },
  { name: 'Logic', symbols: logic },
  { name: 'Geometry', symbols: geometry },
  { name: 'Binary', symbols: binary },
  { name: 'Arrows', symbols: arrows },
  { name: 'Sets', symbols: sets },
  { name: 'Other Symbols', symbols: other_symbols }
]

export default symbols;